export const light = {
    body: "#EAEEF6",
    headerBg: "#FFFFFF",
    headerUser: "#565EEF",
    headerPopUserSetBg: "#FFFFFF",
    headerPopUserSetThemeCheckbox: "#94A6BE",
    cardBg: "#FFFFFF",
    text: "#000000",
    orangeText: "#ff6d00",
    greenText: "#06B16E",
    purpleText: "#9A48F1",
    grayText: "#ffffff",
    orangeBg: "#ffe4c2",
    greenBg: "#B4FDD1",
    purpleBg: "#E9D4FF",
    grayBg: "#94a6be",
};

export const dark = {
    body: "#151419",
    headerBg: "#20202C",
    headerUser: "#FFFFFF",
    headerPopUserSetBg: "#202229",
    headerPopUserSetThemeCheckbox: "#565EEF",
    cardBg: "#20202C",
    text: "#FFFFFF",
    orangeText: "#ffe4c2",
    greenText: "#B4FDD1",
    purpleText: "#E9D4FF",
    grayText: "#94a6be",
    orangeBg: "#ff6d00",
    greenBg: "#06B16E",
    purpleBg: "#9A48F1",
    grayBg: "#ffffff",
};